### ISSUE TITLE
ceph-common version upgrade?

### ISSUE THREAD

**Issue by bzub** [v1k0d3n/bootkube-ci#2]
Hi!  I also like to bundle `ceph-common` into hyperkube, and I had some issues with PVCs getting stuck trying to be mapped to my nodes.  I updated `ceph-common` to the official Ceph Kraken packages and those issues seemed to go away, although I cannot confirm the root cause of the issue.

Anyways, if you're interested in using ceph tools for a recent Ceph release in hyperkube, here's how I did it in the Dockerfile:

before:
```Dockerfile
# [...]
RUN DEBIAN_FRONTEND=noninteractive apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get -yy -q install \
    iptables \
    # [...]
```

after:
```Dockerfile
# [...]
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 08b73419ac32b4e966c1a330e84ac2c0460f3994 \
    && echo "deb http://download.ceph.com/debian-kraken/ jessie main" > /etc/apt/sources.list.d/ceph-kraken.list \
    && DEBIAN_FRONTEND=noninteractive apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get -yy -q install \
    iptables \
    # [...]
```

**Comment by v1k0d3n** [comment]
ah, this is great info. i don't think this will actually be accepted, but since other things like gluster and nfs are included in the official hyperkube image, i thought i would try anyway: https://github.com/kubernetes/kubernetes/pull/46873.

the point you bring up about upgrading to Kraken...this is an interesting point that i will have to explore. i've experienced the same issue, which ends up impacting the deployment for OSH in `./deploy-addons`. if i could get that cleared up it would be a major win! i like your suggestion above better honestly and will try this later today.

thanks for checking out the repo @bzub, and thanks for the info you've been helping us out with in bootkube. it's been really helpful!

**Comment by bzub** [comment]
Hope it helps with the issues you have had.  Glad I'm not the only one!  I'll close this since I'm just sharing info.
