### ISSUE TITLE
feature - openstack-helm-up - using sigil env var 

### ISSUE THREAD

**Issue by gardlt** [v1k0d3n/bootkube-ci#6]
In the openstack-helm-up.sh, there is an export of Sigil but the var is not used. 

Expected: when executing curl use the var to version the pulled version of sigil
Actual: the sigil var is not used.

**Comment by v1k0d3n** [comment]
@gardlt: i'm not sure this is really needed since it's on the POR to remove the sigil requirement all together for OSH. i made a comment here, and still really applies; I'd rather remove it all together if that works for you?

https://github.com/v1k0d3n/bootkube-ci/blob/master/deploy-addons/openstack-helm-up.sh#L29

**Comment by v1k0d3n** [comment]
no response to question, so closing issue.
